
name: AmazonTracker
channels:
- conda-forge
dependencies:
- python=3.7  # keep at python 3.7
- numpy=1.17.5
- pandas=0.25.3
- matplotlib=3.1.2
- jupyter
- jupyterlab=2.0.1
- scipy=1.4.1
- scikit-learn=0.22.1
- pyprojroot=0.2.0
- ipykernel=5.1.4
- seaborn=0.10.0
- pytest=5.3.5
- nodejs=13.9.0
- jinja2=2.11.1
- requests=2.23.0
- beautifulsoup4=4.9.0
- pip  # don't pin this version, we always want latest
- pip:
  - bs4=0.0.1
  - lxml=4.5.0
  # - -e src/.  # this installs your custom package in development mode.